package org.example;

public class Jogador {
    String nome ;
    String sobrenome ;
    String posicoes ;
    String times ;
    Integer idade ;

    //construtor
    public Jogador(String nome, String sobrenome, String posicoes, String times, Integer idade){
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.posicoes = posicoes;
        this.times = times;
        this.idade = idade;

    }
}
